force-app/main/default/objects/Account/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <label>Customer Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preferred_Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Contact_Method__c</fullName>
    <label>Preferred Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Assigned_To_Dealership__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_Dealership__c</fullName>
    <label>Assigned To Dealership</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <label>Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Model_Photo__c.field-meta.xml
<CustomField>
    <fullName>Model_Photo__c</fullName>
    <label>Model Photo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Test Drive</fullName>
            </value>
            <value>
                <fullName>Callback Request</fullName>
            </value>
            <value>
                <fullName>Brochure Download</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/leadClass.cls
public with sharing class leadClass {
    public leadClass() {

    }
    @AuraEnabled(cacheable=true)
    public static List<Lead> getLeads()
    {
        return [SELECT Id, Id__c,Name, Source__c, Outcome__c, Assigned_To_Dealership__c, Prospect__c,Prospect__r.Name, Model_Photo__c,
        Type__c, Model__c, Description, Consultant__c, Consultant__r.Name, Status, CreatedDate FROM Lead WHERE Model__c!=null];
    }
    
    @AuraEnabled(cacheable=false)
    public static Lead getLeadData(Id leadId)
    {
        return [SELECT Id, Id__c,Name, Source__c, Outcome__c, Assigned_To_Dealership__c, Prospect__c,Prospect__r.Name,Model_Photo__c,
                Prospect__r.Mobile__c,Prospect__r.Preferred_Contact_Method__c ,Prospect__r.Customer_Id__c,Prospect__r.Email__c,
        Type__c, Model__c, Description, Consultant__c, Consultant__r.Name, Status, CreatedDate FROM Lead WHERE Id=:leadId];
    }
    
    
    
    
    
}